# This is base config
[http]
    protocol = "http"
    host = "127.0.0.1"
    port = "9090"                       # 监听地址, default ":8700"
    http = "http://127.0.0.1:9090"
    read_timeout = 10                   # 读取超时时长
    write_timeout = 40                  # 写入超时时长
    max_header_bytes = 20               # 最大的header大小，二进制位长度
    allow_ip = [                        # 白名单ip列表
        "127.0.0.1",
    ]

[file]
    view_path = "router/view/*"
    music_file = "file/music"

[mysql]
    [mysql.center_db]
        driver_name = "mysql"
        data_source_name = "sugar:sugar@2021@tcp(rm-wz99n03kfe100hepp5o.mysql.rds.aliyuncs.com:3306)/wkb_v2?charset=utf8&parseTime=true&loc=Asia%2FChongqing"
        max_open_conn = 20
        max_idle_conn = 10
        max_conn_life_time = 100
    [mysql.center_db1]
        driver_name = "mysql"
        data_source_name = "sugar:sugar@2021@tcp(rm-wz99n03kfe100hepp5o.mysql.rds.aliyuncs.com:3306)/wkb_v2?charset=utf8&parseTime=true&loc=Asia%2FChongqing"
        max_open_conn = 20
        max_idle_conn = 10
        max_conn_life_time = 100
    [mysql.business_db]
        driver_name = "mysql"
        data_source_name = "sugar:sugar@2021@tcp(rm-wz99n03kfe100hepp5o.mysql.rds.aliyuncs.com:3306)/wkb_v2?charset=utf8&parseTime=true&loc=Asia%2FChongqing"
        max_open_conn = 20
        max_idle_conn = 10
        max_conn_life_time = 100
    [mysql.business_db1]
        driver_name = "mysql"
        data_source_name = "sugar:sugar@2021@tcp(rm-wz99n03kfe100hepp5o.mysql.rds.aliyuncs.com:3306)/wkb_v2?charset=utf8&parseTime=true&loc=Asia%2FChongqing"
        max_open_conn = 20
        max_idle_conn = 10
        max_conn_life_time = 100

[redis]
    proxy_list = ["127.0.0.1:6379"]
    password = ""
    db = 0
    max_active = 100
    max_idle = 100
    down_grade = false

[log]
    log_level = "trace"         #日志打印最低级别
    [log.file_writer]           #文件写入配置
        on = true
        log_path = "./logs/customer.inf.log"
        rotate_log_path = "./logs/customer.inf.log.%Y%M%D%H"
        wf_log_path = "./logs/customer.wf.log"
        rotate_wf_log_path = "./logs/customer.wf.log.%Y%M%D%H"
    [log.console_writer]        #工作台输出
        on = false
        color = false

[swagger]
    title       = "L C L C F"
    desc        = "L C L C F API"
    host        = "127.0.0.1:9090"
    base_path   = "/customer"