// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "微信"
                ],
                "summary": "登录",
                "operationId": "/login",
                "parameters": [
                    {
                        "description": "body",
                        "name": "polygon",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/interfaceStruct.LoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/interfaceStruct.LoginOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "interfaceStruct.LoginInput": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "用户id",
                    "type": "integer",
                    "example": 1
                },
                "openid": {
                    "description": "用户应用id",
                    "type": "string",
                    "example": "1"
                },
                "union_id": {
                    "description": "用户唯一id",
                    "type": "string",
                    "example": "1"
                },
                "user_id": {
                    "description": "用户userId",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "interfaceStruct.LoginOutput": {
            "type": "object",
            "properties": {
                "age": {
                    "description": "用户年龄",
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "description": "用户id",
                    "type": "integer",
                    "example": 1
                },
                "job": {
                    "description": "用户职业",
                    "type": "string",
                    "example": "1"
                },
                "name": {
                    "description": "用户昵称",
                    "type": "string",
                    "example": "1"
                },
                "openid": {
                    "description": "用户应用id",
                    "type": "string",
                    "example": "1"
                },
                "remark": {
                    "description": "用户备注",
                    "type": "string",
                    "example": "1"
                },
                "union_id": {
                    "description": "用户唯一id",
                    "type": "string",
                    "example": "1"
                },
                "user_id": {
                    "description": "用户userId",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "middleware.Response": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "errmsg": {
                    "type": "string"
                },
                "errno": {
                    "type": "integer"
                },
                "stack": {
                    "type": "object"
                },
                "trace_id": {
                    "type": "object"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
